# .github/workflows/norminette.yml
name: norminette_V3
<<<<<<< HEAD
on: [push, pull_request]
=======
on:
  push:
    branches:
      - V3
>>>>>>> V3
jobs:

  norminette_v3_job:
    runs-on: ubuntu-latest
    name: norminette v3
    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v3
=======
    - uses: actions/checkout@v2
>>>>>>> V3
    - uses: alexandregv/norminette-action@v3
